### PR TITLE
Enhance UX for the browser action, possibility to disable popup

### PR DESCRIPTION
**Pull request by szachara**
Added possibility to enable / disable XDebug Session only by left click on xdebug helper icon.

### CODE REVIEW

**Comment by szachara** [comment]
It's done, I tested edge cases too, like when you have selected trace, then go to options, you disable popup and then click on icon, so in this case will be disabled.

I tested keyboard shortcuts too.

I will test it again tomorrow and this PR will be ready, pls look at it and give some feedback, thx.

**Comment by szachara** [comment]
Tested again today and every thing looks good 🏠

**Comment by gazugafan** [comment]
Can confirm it works great for me. Just what I was looking for after switching to Vivaldi, and here it is already done! Hope it gets merged into the master branch!

**Comment by mac-cain13** [comment]
Thanks for the reminder, I should really merge and release this. I will hit the merge button right now, and try to release it asap. :)

**Pull request merged**
